name: main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: download
      uses: actions/download-artifact@master
      with:
        name: build-artifact
        path: build
    - name: build
      uses: ./
      with:
        args: -v .:/build
    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: build